SELECT CATENTRY.PARTNUMBER, 
CASE WHEN CATENTSHIP.WEIGHT = 1 
  THEN 'Grande' 
  ELSE 'Pequeño' 
END  AS WEIGHT,
CALCODE.CODE
FROM CATENTRY
JOIN CATENTDESC ON CATENTDESC.CATENTRY_ID = CATENTRY.CATENTRY_ID
JOIN CATENCALCD ON CATENTRY.CATENTRY_ID = CATENCALCD.CATENTRY_ID
JOIN CALCODE ON CALCODE.CALCODE_ID = CATENCALCD.CALCODE_ID
JOIN CATENTSHIP ON CATENTSHIP.CATENTRY_ID = CATENTRY.CATENTRY_ID
WHERE CATENTRY.MARKFORDELETE = 0 AND CATENTRY.CATENTTYPE_ID = 'ProductBean' AND CALCODE.CALUSAGE_ID = -2 AND CATENTDESC.PUBLISHED = 1



